name = "open-data-portal"
main = "./src/worker/index.ts"
compatibility_date = "2025-11-17"

[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/api/*", "/docs*", "/openapi*"]

[[d1_databases]]
binding = "DB"
database_name = "open-data-db"
database_id = "" # fill in database id

[observability]
enabled = true
