name = "open-data-portal"
main = "src/index.ts"
compatibility_date = "2025-11-17"

[assets]
directory = './public'

[[d1_databases]]
binding = "DB"
database_name = "open-data-db"
database_id = "" # fill in database id

[observability]
enabled = true
